---
- hosts: hetzner
  # become: yes
# - hosts: local

  vars:
    - user: ivan

  tasks:
    - name: Add user
      ansible.builtin.user:
        name: '{{ user }}'
        shell: /bin/bash
        groups: sudo,docker
        system: true
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ivan
        state: present
        manage_dir: false
        key: "{{ lookup('file', '/Users/ivan/.ssh/id_rsa.pub') }}"
    - name: Install base packages
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    - name: Create dir for keyrings
      ansible.builtin.file:
        dest: /etc/apt/keyrings
        state: directory
    - name: Set docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Create docker cli dir
      ansible.builtin.file:
        dest: "/home/{{ user }}/.docker/cli-plugins"
        state: directory
    - name: Install docker packages
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
        - binfmt-support
        - containerd.io
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - qemu
        - qemu-system
        - qemu-user-static
    - name: Set docker
      shell: |
        wget -c https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-amd64 -P "/home/{{ user }}/.docker/cli-plugins"
        docker buildx install
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
        docker run --privileged --rm tonistiigi/binfmt --install arm64,arm
    - name: Set syncthing repo
      shell: |
        curl -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg

        echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | tee /etc/apt/sources.list.d/syncthing.list
    - name: Install syncthing
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - syncthing
    - name: Setup syncthing auto-launch
      shell: |
        systemctl enable syncthing@{{ user }}.service
        systemctl start syncthing@{{ user }}.service
    - name: Add 1password repo
      shell: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list

        mkdir -p /etc/debsig/policies/AC2D62742012EA22/
        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --yes --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    - name: Install packages
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
        - fzf
        - git
        - htop
        - neovim
        - tmux
        - ripgrep
        - file
        - command-not-found
        - 1password-cli
    - name: Install deb-get
      ansible.builtin.get_url:
        url: https://github.com/wimpysworld/deb-get/releases/download/0.3.6/deb-get_0.3.6-1_all.deb
        dest: /tmp/deb-get_0.3.6-1_all.deb
    - name: Install a .deb package
      ansible.builtin.apt:
        deb: /tmp/deb-get_0.3.6-1_all.deb
    - name: Install packages with deb-get
      shell: |
        deb-get install '{{ item }}'
      with_items:
        - du-dust
