---
# - hosts: hetzner
- hosts: local

  tasks:
    - name: Install base packages
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    - name: Create dir for keyrings
      ansible.builtin.file:
        dest: /etc/apt/keyrings
        state: directory
    - name: Set docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Create docker cli dir
      ansible.builtin.file:
        dest: $HOME/.docker/cli-plugins
        state: directory
    - name: Set docker
      shell: |
        wget -c https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-amd64 -P $HOME/.docker/cli-plugins
        docker buildx install
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
    - name: Create a syncthing config
      ansible.builtin.template:
        src: ./syncthing.service
        dest: /etc/systemd/system/syncthing.service
        owner: root
        group: root
        mode: 0644
    - name: Add 1password repo
      shell: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list

        mkdir -p /etc/debsig/policies/AC2D62742012EA22/
        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --yes --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    - name: Install packages
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      with_items:
        - binfmt-support
        - containerd.io
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - fzf
        - git
        - htop
        - neovim
        - qemu
        - qemu-system
        - qemu-user-static
        - tmux
        - 1password
